# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: neuro_san/api/grpc/tasks_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'neuro_san/api/grpc/tasks_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&neuro_san/api/grpc/tasks_service.proto\x12\x1e\x64\x65v.cognizant_ai.neuroai.tasks\"\x81\x02\n\x12\x44\x61tasetTaskRequest\x12\x18\n\x07task_id\x18\x01 \x01(\tR\x07task_id\x12 \n\x0b\x63ode_source\x18\x02 \x01(\tR\x0b\x63ode_source\x12(\n\x0f\x64\x65stination_uri\x18\x03 \x01(\tR\x0f\x64\x65stination_uri\x12V\n\x06params\x18\x04 \x03(\x0b\x32>.dev.cognizant_ai.neuroai.tasks.DatasetTaskRequest.ParamsEntryR\x06params\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x91\x01\n\x13\x44\x61tasetTaskResponse\x12\x18\n\x07task_id\x18\x01 \x01(\tR\x07task_id\x12\x42\n\x06status\x18\x02 \x01(\x0e\x32*.dev.cognizant_ai.neuroai.tasks.TaskStatusR\x06status\x12\x1c\n\terror_msg\x18\x03 \x01(\tR\terror_msg\"-\n\x11TaskStatusRequest\x12\x18\n\x07task_id\x18\x01 \x01(\tR\x07task_id\"\x90\x01\n\x12TaskStatusResponse\x12\x18\n\x07task_id\x18\x01 \x01(\tR\x07task_id\x12\x42\n\x06status\x18\x02 \x01(\x0e\x32*.dev.cognizant_ai.neuroai.tasks.TaskStatusR\x06status\x12\x1c\n\terror_msg\x18\x03 \x01(\tR\terror_msg*y\n\nTaskStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\x0b\n\x07SUCCESS\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x12\x11\n\rINVALID_INPUT\x10\x04\x12\x12\n\x0e\x41LREADY_EXISTS\x10\x05\x12\x12\n\x0e\x44OES_NOT_EXIST\x10\x06\x32\x85\x02\n\x0bTaskService\x12|\n\x0fGenerateDataset\x12\x32.dev.cognizant_ai.neuroai.tasks.DatasetTaskRequest\x1a\x33.dev.cognizant_ai.neuroai.tasks.DatasetTaskResponse\"\x00\x12x\n\rGetTaskStatus\x12\x31.dev.cognizant_ai.neuroai.tasks.TaskStatusRequest\x1a\x32.dev.cognizant_ai.neuroai.tasks.TaskStatusResponse\"\x00\x42^Z\\github.com/leaf-ai/unileaf/internal/gen/dev.cognizant_dev.ai/genproto/unileaf/tasks/v1;tasksb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'neuro_san.api.grpc.tasks_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\\github.com/leaf-ai/unileaf/internal/gen/dev.cognizant_dev.ai/genproto/unileaf/tasks/v1;tasks'
  _globals['_DATASETTASKREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_DATASETTASKREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_TASKSTATUS']._serialized_start=676
  _globals['_TASKSTATUS']._serialized_end=797
  _globals['_DATASETTASKREQUEST']._serialized_start=75
  _globals['_DATASETTASKREQUEST']._serialized_end=332
  _globals['_DATASETTASKREQUEST_PARAMSENTRY']._serialized_start=287
  _globals['_DATASETTASKREQUEST_PARAMSENTRY']._serialized_end=332
  _globals['_DATASETTASKRESPONSE']._serialized_start=335
  _globals['_DATASETTASKRESPONSE']._serialized_end=480
  _globals['_TASKSTATUSREQUEST']._serialized_start=482
  _globals['_TASKSTATUSREQUEST']._serialized_end=527
  _globals['_TASKSTATUSRESPONSE']._serialized_start=530
  _globals['_TASKSTATUSRESPONSE']._serialized_end=674
  _globals['_TASKSERVICE']._serialized_start=800
  _globals['_TASKSERVICE']._serialized_end=1061
# @@protoc_insertion_point(module_scope)
