#!/usr/bin/env bash

# Copyright (C) 2023-2024 Cognizant Digital Business, Evolutionary AI.
# All Rights Reserved.
# Issued under the Academic Public License.
#
# You can be released from the terms, and requirements of the Academic Public
# License by purchasing a commercial license.
# Purchase of a commercial license is mandatory for any use of the
# neuro-san SDK Software in commercial settings.
#
# END COPYRIGHT

# This script will:
# 1) Generate GRPC code for any services (generated or not) from its PROTO_FILE
# 2) Modify the code generated by protoc to conform to Python 3
#    by fully specifying package paths for local imports.

# Find out where we are
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Define some directories relative to where we are
# Note: All the protobuf guides say to not mix absolute and relative paths
#       So we pick absolute paths.
ONE_LEVEL_UP=${DIR%/*}
COMMON_PARENT_DIR=${ONE_LEVEL_UP}
# Up on more directory is the top level
TOP_LEVEL=${COMMON_PARENT_DIR%/*}
GENERATED_DIR=${DIR}/generated
PROTOS_DIR=${TOP_LEVEL}/proto

# Ordering matters w/rt where generated file is output
PROTO_PATH="--proto_path=${GENERATED_DIR} \
            --proto_path=proto \
            --proto_path=${PROTOS_DIR}"
echo "PROTO_PATH is ${PROTO_PATH}"

# Inputs to the script
LOCAL_PROTO_FILES=$(< "${PROTOS_DIR}"/backend_shared_proto.txt)

PACKAGE="neuro_san.grpc.generated"

# Note that these files cannot have a service defined in them, otherwise there
# will be problems with references from the _pb2_grpc.py file.
CHANGE_IMPORTS="agent_pb2 \
                chat_pb2 \
                common_structs_pb2 \
                image_data_pb2 \
                user_pb2"


echo "Generating gRPC code in ${GENERATED_DIR}..."

# Create the generated directory if it doesn't exist already
mkdir -p "${GENERATED_DIR}"

# Create a file so that the python compiler can find source in the new dir.
touch "${GENERATED_DIR}"/__init__.py

# Copy over external proto files
ALL_PROTO_FILES=""
ALL_PROTO_FILES="${ALL_PROTO_FILES} ${LOCAL_PROTO_FILES}"


# Generate the python files and make them happy w/rt Python 3
for PROTO_FILE in ${ALL_PROTO_FILES}
do
    PROTO_BASE=$(basename "${PROTO_FILE}")

    # 2) Generate the GRPC code for a single service proto file.
    echo "generating gRPC code for ${PROTO_FILE}."
    # shellcheck disable=SC2086    # PROTO_PATH is compilation of cmd line args
    python -m grpc_tools.protoc ${PROTO_PATH} \
        --python_out="${GENERATED_DIR}" \
        --grpc_python_out="${GENERATED_DIR}" \
        "${PROTO_FILE}"

    echo "Modifying gRPC code for Python 3 for ${PROTO_FILE}"

    # 3) Modify the generated code for fully specified python 3 packages.
    # Derive the file names and import we are looking for from the PROTO_FILE
    GRPC_FILE=${PROTO_BASE/.proto/_pb2_grpc.py}
    PY3_GRPC_FILE=${PROTO_BASE/.proto/_pb2_grpc_py3.py}
    PB2_FILE=${PROTO_BASE/.proto/_pb2.py}
    PY3_PB2_FILE=${PROTO_BASE/.proto/_pb2_py3.py}

    #
    # Change the import of the _pb2 file to have a full python package path.
    #
    IMPORT=${PROTO_BASE/.proto/_pb2}

    # Find the line we want to change with local imports which are no good
    # for py3 and create a new line we want to use with fully-specified imports.
    import_line=$(grep "import ${IMPORT}" < "${GENERATED_DIR}"/"${GRPC_FILE}")
    new_import_line=${import_line/${IMPORT}/${PACKAGE}.${IMPORT}}

    # Create a new file with the new import lines.
    # Note this does not preserve the order of imports,
    # but that's ok.
    echo "$new_import_line" > "${GENERATED_DIR}"/"${PY3_GRPC_FILE}"
    grep -v " ${IMPORT} " < "${GENERATED_DIR}"/"${GRPC_FILE}" >> \
         "${GENERATED_DIR}"/"${PY3_GRPC_FILE}"

    # Move the python3 file into replace the generated file
    mv "${GENERATED_DIR}"/"${PY3_GRPC_FILE}" "${GENERATED_DIR}"/"${GRPC_FILE}"

    for CHANGE_IMPORT in ${CHANGE_IMPORTS}
    do
        #
        # Change the import of the CHANGE_IMPORT file
        # to have a full python package path.
        #
        if [ "${IMPORT}" != "${CHANGE_IMPORT}" ]
        then
            IMPORT=${CHANGE_IMPORT}

            # Find the line we want to change with local imports which are no good
            # for py3 and create a new line we want to use with fully-specified imports.
            import_line=$(grep "import ${IMPORT}" < "${GENERATED_DIR}"/"${GRPC_FILE}")
            new_import_line=${import_line/${IMPORT}/${PACKAGE}.${IMPORT}}

            # Create a new file with the new import lines.
            # Note this does not preserve the order of imports,
            # but that's ok.
            echo "$new_import_line" > "${GENERATED_DIR}"/"${PY3_GRPC_FILE}"
            grep -v " ${IMPORT} " < "${GENERATED_DIR}"/"${GRPC_FILE}" >> \
                "${GENERATED_DIR}"/"${PY3_GRPC_FILE}"

            # Move the python3 file into replace the generated file
            mv "${GENERATED_DIR}"/"${PY3_GRPC_FILE}" "${GENERATED_DIR}"/"${GRPC_FILE}"
        fi

        #
        # Change the import of the CHANGE_IMPORT file
        # to have a full python package path.
        #
        IMPORT=${CHANGE_IMPORT}

        # Find the line we want to change with local imports which are no good
        # for py3 and create a new line we want to use with fully-specified imports.
        import_line=$(grep "import ${IMPORT}" < "${GENERATED_DIR}"/"${PB2_FILE}")
        new_import_line=${import_line/${IMPORT}/${PACKAGE}.${IMPORT}}

        # Create a new file with the new import lines.
        # Note this does not preserve the order of imports,
        # but that's ok.
        echo "$new_import_line" > "${GENERATED_DIR}"/"${PY3_PB2_FILE}"
        grep -v " ${IMPORT} " < "${GENERATED_DIR}"/"${PB2_FILE}" >> \
             "${GENERATED_DIR}"/"${PY3_PB2_FILE}"

        # Move the python3 file into replace the generated file
         mv "${GENERATED_DIR}"/"${PY3_PB2_FILE}" "${GENERATED_DIR}"/"${PB2_FILE}"
    done
done
